baseURL = 'https://apexliveapi.com/'
languageCode = 'en-us'
title = 'LiveAPI 2.0 Documentation'
enableEmoji = true
enableGitInfo = true

[params]
    ghrepo = "https://github.com/zeejayym/apex-liveapi-documentation" 
    ghbranch = "master"

[module]
    # uncomment line below for temporary local development of module
    # or when using a 'theme' as a git submodule
    replacements = "github.com/colinwilson/lotusdocs -> lotus"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[params.docs]	
    darkMode = true
    title = "LiveAPI 2.0 Documentation"

    repoURL = "https://github.com/zeejayym/apex-liveapi-documentation"
    repoBranch = "master"
    editPage = true

    lastMod = true
    themeColor = "blue"
    prism = true
    sidebarIcons = true
    titleIcon = true


[params.footer]
    copyright = "Built by zeejayym. Not affiliated with EA or Respawn Entertainment. Powered by Hugo and lotusdocs."

[params.social]
    github = "zeejayym/apex-liveapi-documentation"
    twitter = "zeejayym"